### ISSUE TITLE
When writing acceptance tests, it's not possible to use an '=' in the value of an assertion.

### ISSUE THREAD

**Issue by tobycatlin** [BladeRunnerJS/brjs#1008]
When writing acceptance tests, it's not possible to use an '=' in the value of an assertion.
E.g.
```
it("binds the currency displayed to the instrument", function()
{
 given("ticket.viewOpened = true");
 when("ticket.model.ticketHeader.currencyPair => 'USDGBP'");
 then("ticket.view.(.execute-container .dealt-currency).text = 'USD='");
});
```
will give an error along the lines of:
`binds the currency displayed to the instrument failed (237,00 ms): InvalidPropertyValueError: InvalidPropertyValueError: Error handling statement 'ticket.view.(.execute-container .dealt-currency).text = 'USD='': 'null' is not a valid type (only strings, numbers, booleans and undefined are supported)`

This is because of the regex used in GwtTestRunner (line 495) to parse the statement:
`/(.+)(\=\>|\=)(.+)/i`
A simple fix seems to be to enforce a space around the operator, so that the regex reads:
`/(.+)( \=\>|\= )(.+)/i`

internal URL for this issue - http://yourls.caplin.com/5

**Comment by ioanalianabalas** [comment]
Fixed by #1163.

**Comment by thecapdan** [comment]
@ioanalianabalas testing this fix in the branch - it is still not possible to use an "=" sign in the assertion value.

To reproduce, use PropertyTest, and change line 11 to:

```
and("demo.view.(span#prop-formatted).text = 'A='");
```

**Comment by ioanalianabalas** [comment]
@thecapdan, it's been fixed now.

**Comment by thecapdan** [comment]
works now. also tested with doWhens which also work when assigning a value that contains an equals.
